### ISSUE TITLE
Can't install doors because of missing xtrn.cnf

### ISSUE THREAD

**Issue by runningopenloop** [SynchronetBBS/sbbs#4] opened 2023-01-15 09:20 UTC
Hi,
I've installed sbbs as per instructions for linux.  I installed using using GIT with no tag specified.

sbbs@myhost:/sbbs/repo
$ git show master
commit 8f126a2f682407e9783cc2cc00f9d687b44bc353 (HEAD -> master, origin/master, origin/HEAD)
Merge: e8944f5bd f43a3ff73
Author: Rob Swindell <rob@synchro.net>
Date:   Sun Jan 15 01:29:38 2023 +0000
...

---

Goal is teach my children about the glory days of gaming on BBSes.  :)

 * I've been quite happy with my progress, everything setup smoothly.
 * Even got dosemu installed no apparent problems.  (Looks like I may need to upgrade to FreeDOS-1.3 at some point vs. the 1.0 for TradeWars 2002?

I'm running into trouble installing the external programs as below... (I've tried through the BBS also, same issue).

I'm following this...
http://wiki.synchro.net/howto:door:index?s[]=install&s[]=door

/sbbs/exec/jsexec /sbbs/exec/install-xtrn.js

`...
 31: /sbbs/xtrn/tw2/
 32: /sbbs/xtrn/uberblox/
 33: /sbbs/xtrn/war/
 34: /sbbs/xtrn/wordem/
Which or [Q]uit: 31
******************************************************************
* Installing /sbbs/xtrn/tw2/install-xtrn.ini use Ctrl-C to abort *
******************************************************************
Install file: 2020/09/20
[ Trade Wars 2 - 500 Sectors ]
A multiplayer game that is a cross between a war game and a space trading game.
By: Chris Sherrick, John Morris, ported to Sync-JS by Deuce (Stephen Hurd)
Categories: Games
Sub-categories: Space, War, Trade, Classic, Multiplayer, JavaScript, Port
!Failed to read /sbbs/ctrl/xtrn.cnf
Installed 0 external programs.
/sbbs/./exec/install-xtrn.js executed in 3.61 seconds

JavaScript: Destroying context
JavaScript: Destroying runtime
sbbs@myhost:/sbbs
$ 
`

If I, for grins "touch /sbbs/ctrl/xtrn.cnf" -- I get the below.
`
 31: /sbbs/xtrn/tw2/
 32: /sbbs/xtrn/uberblox/
 33: /sbbs/xtrn/war/
 34: /sbbs/xtrn/wordem/
Which or [Q]uit: 31
******************************************************************
* Installing /sbbs/xtrn/tw2/install-xtrn.ini use Ctrl-C to abort *
******************************************************************
Install file: 2020/09/20
[ Trade Wars 2 - 500 Sectors ]
A multiplayer game that is a cross between a war game and a space trading game.
By: Chris Sherrick, John Morris, ported to Sync-JS by Deuce (Stephen Hurd)
Categories: Games
Sub-categories: Space, War, Trade, Classic, Multiplayer, JavaScript, Port
!JavaScript  /sbbs/./exec/install-xtrn.js line 133: TypeError: objs is undefined
/sbbs/./exec/install-xtrn.js executed in 2.11 seconds
!Module (./exec/install-xtrn.js) set exit_code: 1

JavaScript: Destroying context
JavaScript: Destroying runtime

Returning error code: 1
sbbs@myhost:/sbbs
$ 
`

My understanding is the xtrn.cnf is no longer used and xtrn.ini has replaced it.  However it seems there is an issue here.  The simple install script doesn't yet support xtrn.ini?

---

Is there a reason  Operation Overkill II is not in the list for simple install?  (Because it is not a javascript game?) and needs to be done manually, just refer to the link below?
http://wiki.synchro.net/howto:door:ooii

**Comment by rswindell** [comment] 2023-01-16 00:29
This is a duplicate of https://gitlab.synchro.net/main/sbbs/-/issues/473

And this is the wrong place to submit Synchronet issues.

**Comment by rswindell** [comment] 2023-01-16 20:53
Closing as duplicate (copied details provided above to gitlab issue 473).

**Closed by rswindell** 2023-01-16 20:53 UTC
